package com.bamuel.pokemonjourney;

public class Pokemon {

    public String IDtoName(int PKMN_ID) {
        switch (PKMN_ID) {
            case 1:
                return "Bulbasaur";
            case 2:
                return "Ivysaur";
            case 3:
                return "Venusaur";
            case 4:
                return "Charmander";
            case 5:
                return "Charmeleon";
            case 6:
                return "Charizard";
            case 7:
                return "Squirtle";
            case 8:
                return "Wartortle";
            case 9:
                return "Blastoise";
            case 10:
                return "Caterpie";
            case 11:
                return "Metapod";
            case 12:
                return "Butterfree";
            case 13:
                return "Weedle";
            case 14:
                return "Kakuna";
            case 15:
                return "Beedrill";
            case 16:
                return "Pidgey";
            case 17:
                return "Pidgeotto";
            case 18:
                return "Pidgeot";
            case 19:
                return "Rattata";
            case 20:
                return "Raticate";
            case 21:
                return "Spearow";
            case 22:
                return "Fearow";
            case 23:
                return "Ekans";
            case 24:
                return "Arbok";
            case 25:
                return "Pikachu";
            case 26:
                return "Raichu";
            case 27:
                return "Sandshrew";
            case 28:
                return "Sandslash";
            case 29:
                return "Nidoran-F";
            case 30:
                return "Nidorina";
            case 31:
                return "Nidoqueen";
            case 32:
                return "Nidoran-M";
            case 33:
                return "Nidorino";
            case 34:
                return "Nidoking";
            case 35:
                return "Clefairy";
            case 36:
                return "Clefable";
            case 37:
                return "Vulpix";
            case 38:
                return "Ninetales";
            case 39:
                return "Jigglypuff";
            case 40:
                return "Wigglytuff";
            case 41:
                return "Zubat";
            case 42:
                return "Golbat";
            case 43:
                return "Oddish";
            case 44:
                return "Gloom";
            case 45:
                return "Vileplume";
            case 46:
                return "Paras";
            case 47:
                return "Parasect";
            case 48:
                return "Venonat";
            case 49:
                return "Venomoth";
            case 50:
                return "Diglett";
            case 51:
                return "Dugtrio";
            case 52:
                return "Meowth";
            case 53:
                return "Persian";
            case 54:
                return "Psyduck";
            case 55:
                return "Golduck";
            case 56:
                return "Mankey";
            case 57:
                return "Primeape";
            case 58:
                return "Growlithe";
            case 59:
                return "Arcanine";
            case 60:
                return "Poliwag";
            case 61:
                return "Poliwhirl";
            case 62:
                return "Poliwrath";
            case 63:
                return "Abra";
            case 64:
                return "Kadabra";
            case 65:
                return "Alakazam";
            case 66:
                return "Machop";
            case 67:
                return "Machoke";
            case 68:
                return "Machamp";
            case 69:
                return "Bellsprout";
            case 70:
                return "Weepinbell";
            case 71:
                return "Victreebel";
            case 72:
                return "Tentacool";
            case 73:
                return "Tentacruel";
            case 74:
                return "Geodude";
            case 75:
                return "Graveler";
            case 76:
                return "Golem";
            case 77:
                return "Ponyta";
            case 78:
                return "Rapidash";
            case 79:
                return "Slowpoke";
            case 80:
                return "Slowbro";
            case 81:
                return "Magnemite";
            case 82:
                return "Megneton";
            case 83:
                return "Farfetch'd";
            case 84:
                return "Doduo";
            case 85:
                return "Dodrio";
            case 86:
                return "Seel";
            case 87:
                return "Dewgong";
            case 88:
                return "Grimer";
            case 89:
                return "Muk";
            case 90:
                return "Shellder";
            case 91:
                return "Cloyster";
            case 92:
                return "Gastly";
            case 93:
                return "Haunter";
            case 94:
                return "Gengar";
            case 95:
                return "Onix";
            case 96:
                return "Drowzee";
            case 97:
                return "Hypno";
            case 98:
                return "Krabby";
            case 99:
                return "Kingler";
            case 100:
                return "Voltorb";
            case 101:
                return "Electrode";
            case 102:
                return "Exeggcute";
            case 103:
                return "Exeggutor";
            case 104:
                return "Cubone";
            case 105:
                return "Marowak";
            case 106:
                return "Hitmonlee";
            case 107:
                return "Hitmonchan";
            case 108:
                return "Lickitung";
            case 109:
                return "Koffing";
            case 110:
                return "Weezing";
            case 111:
                return "Rhyhorn";
            case 112:
                return "Rhydon";
            case 113:
                return "Chansey";
            case 114:
                return "Tangela";
            case 115:
                return "Kangaskhan";
            case 116:
                return "Horsea";
            case 117:
                return "Seadra";
            case 118:
                return "Goldeen";
            case 119:
                return "Seaking";
            case 120:
                return "Staryu";
            case 121:
                return "Starmie";
            case 122:
                return "Mr. Mime";
            case 123:
                return "Scyther";
            case 124:
                return "Jynx";
            case 125:
                return "Electabuzz";
            case 126:
                return "Magmar";
            case 127:
                return "Pinsir";
            case 128:
                return "Tauros";
            case 129:
                return "Magikarp";
            case 130:
                return "Gyarados";
            case 131:
                return "Lapras";
            case 132:
                return "Ditto";
            case 133:
                return "Eevee";
            case 134:
                return "Vaporeon";
            case 135:
                return "Jolteon";
            case 136:
                return "Flareon";
            case 137:
                return "Porygon";
            case 138:
                return "Omanyte";
            case 139:
                return "Omastar";
            case 140:
                return "Kabuto";
            case 141:
                return "Kabutops";
            case 142:
                return "Aerodactyl";
            case 143:
                return "Snorlax";
            case 144:
                return "Articuno";
            case 145:
                return "Zapdos";
            case 146:
                return "Moltres";
            case 147:
                return "Dratini";
            case 148:
                return "Dragonair";
            case 149:
                return "Dragonite";
            case 150:
                return "Mewtwo";
            case 151:
                return "Mew";
            default:
                return "ERROR";
        }
    }

}
